### ISSUE TITLE
pip and/or conda install

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/turb_client#4]
We need this to ease the installing of FOQUS. See issue https://github.com/CCSI-Toolset/FOQUS/issues/161

**Comment by boverhof** [comment]
## Register with Pypi
## Create  File with Pypi credentials
```
turb_client % cat ~/.pypirc 

[distutils]
index-servers=
    pypi
    pypitest

[pypi]
username = ######
password = ######

[pypitest]
repository = https://test.pypi.org/legacy/
username = ########
password = ########
```
## Change "setup.py" License classifier to one of options found here: 
https://pypi.org/pypi?%3Aaction=list_classifiers
```
turb_client % grep -A9 classifiers setup.py 
    classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Intended Audience :: End Users/Desktop",
        "License :: Other/Proprietary License",
        "Programming Language :: Python",
        "Natural Language :: English",
        "Operating System :: POSIX"
    ],
```
## Register with Pypi
```
turb_client % python setup.py register sdist upload
```
## PIP Install
```
(python2) test % pip install TurbineClient
```

**Comment by CSRussell2319** [comment]
I tried to use pip to install TurbineClient and received the following error:

---------------------------------------------------------------------------------
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting Flask-Testing (from -r C:\Users\foqus_tester\Documents\GitHub\FOQUS\FOQUS\condaenv.8tn3pt.requirements.txt (line 1))
Collecting cma (from -r C:\Users\foqus_tester\Documents\GitHub\FOQUS\FOQUS\condaenv.8tn3pt.requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7f/61/f64befe7db81816728a284f0bbd6b4acda1518a2231b4e436bf646b10875/cma-2.6.0-py2.py3-none-any.whl
Collecting adodbapi (from -r C:\Users\foqus_tester\Documents\GitHub\FOQUS\FOQUS\condaenv.8tn3pt.requirements.txt (line 3))
Collecting python-ntlm (from -r C:\Users\foqus_tester\Documents\GitHub\FOQUS\FOQUS\condaenv.8tn3pt.requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/20/1a/89ea049b646d2a8fc61ed9ead7a92118ab4a9dba8b9af5e1e29f95e86175/python_ntlm-1.1.0-py2-none-any.whl
Collecting TurbineClient (from -r C:\Users\foqus_tester\Documents\GitHub\FOQUS\FOQUS\condaenv.8tn3pt.requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/2e/9b/4a62a2020806aec2fd68874787ef88a8564b2699c6152f1cbc8ae98fb44c/TurbineClient-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\foqus_~1\appdata\local\temp\pip-install-dae2og\TurbineClient\setup.py", line 13, in <module>
        from ez_setup import use_setuptools
    ImportError: No module named ez_setup

Command "python setup.py egg_info" failed with error code 1 in c:\users\foqus_~1\appdata\local\temp\pip-install-dae2og\TurbineClient\

CondaValueError: pip returned an error

----------------------------------------------------------------------------------------------------------

**Comment by ksbeattie** [comment]
@ksbeattie needs to get to this.

**Comment by ksbeattie** [comment]
@ksbeattie still will try to get to this.

**Comment by eslickj** [comment]
I looked at our license file and the contents sure look like BSD 3 clause, if we need the proper license classification for this.

**Comment by ksbeattie** [comment]
I've uploaded a new dev/release candidate package to the test.pypi index.

@CSRussell2319 could you test by using `pip install -i https://test.pypi.org/simple/ TurbineClient` rather than what is in FOQUS' requirements.txt?

Will this also help with issues of those running behind restrictive firewalls?

**Comment by ksbeattie** [comment]
@boverhof is testing this with python 3

**Comment by ksbeattie** [comment]
I believe this is fixed.  Cutting a new release, creating and uploading a new package to pypi.org will be the test.
