### ISSUE TITLE
Python 3 compatability

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/turb_client#5]
This is the equivalent of: https://github.com/CCSI-Toolset/FOQUS/issues/334

**Comment by boverhof** [comment]
Initial work is done, all suites in turbine client are working against a TurbineLite instance in AWS/EC2

Also have done initial testing with FOQUS and ran the tests there with success.  

Please test ( @eslickj , @CSRussell2319, @fsoepyan ) FOQUS with  https://github.com/CCSI-Tools/turb_client.git

pull request https://github.com/CCSI-Toolset/turb_client/pull/6

**Comment by boverhof** [comment]
Tested and seems to be working.  Open new issues to address problems.
